site_name: MOSEC
site_url: https://mosecorg.github.io/mosec
site_description: Model Serving made Efficient in the Cloud

repo_name: mosecorg/mosec
repo_url: https://github.com/mosecorg/mosec

nav:
  - Home:
      - Overview: "index.md"
      - Interface: "interface.md"
      - Argument: "argument.md"
      - Contributing: "contributing.md"
  - Design:
      - Overview: "design/index.md"
  - Example:
      - Overview: "example/index.md"
      - Echo: "example/echo.md"
      - Jax: "example/jax.md"
      - PyTorch: "example/pytorch.md"
      - Metrics: "example/metric.md"
      - Environments: "example/env.md"
      - Demo - Stable Diffusion: "example/stable_diffusion.md"
      - Plugins - IPCWrapper: "example/ipc.md"
  # - Deploy: "deploy.md"
  # - FAQ: "faq.md"
  # - Benchmark: "BENCHMARK.md"

theme:
  name: "material"
  favicon: https://user-images.githubusercontent.com/38581401/134798617-0104dc12-e0d4-4ed5-a79c-9e2435e99a14.png
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: grey
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "Â¤"

plugins:
  - search:
      lang: en
  - gen-files:
      scripts:
        - scripts/gen_docs_args.py
  - mkdocstrings:
      watch:
        - mosec
        - scripts
        - examples
        - README.md
        - CONTRIBUTING.md
      handlers:
        python:
          rendering:
            show_root_heading: yes
            show_object_full_path: yes
            show_signature_annotations: yes

extra_css:
  - styles/extra.css
