# https://peps.python.org/pep-0621/
[project]
name = "mosec"
description = "Model Serving made Efficient in the Cloud"
readme = "README.md"
authors = [
    {name = "Keming", email = "kemingy94@gmail.com"},
    {name = "Zichen", email = "lkevinzc@gmail.com"}
]
license = {text = "Apache-2.0"}
keywords = ["machine learning", "deep learning", "model serving"]
dynamic = ["version"]
requires-python = ">=3.6"
classifiers = [
    "Environment :: GPU",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Rust",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Build Tools",
]

[project.urls]
homepage = "https://mosecorg.github.io/"
documentation = "https://mosecorg.github.io/mosec/"
repository = "https://github.com/mosecorg/mosec"
changelog = "https://github.com/mosecorg/mosec/releases"

[tool.cibuildwheel]
build-frontend = "build"
skip = "cp36-*"
archs = ["auto64"]
before-all = "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
environment = { PRODUCTION_MODE="yes", PATH="$PATH:$HOME/.cargo/bin", PIP_NO_CLEAN="yes" }
before-build = "git status" # help to debug what happened to the setuptools_scm (file changes)

[project.optional-dependencies]

[project.scripts]

[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=7.0"]

[tool.setuptools_scm]
write_to = "mosec/_version.py"

[tool.mypy]
warn_redundant_casts = true
warn_unreachable = true
pretty = true

[tool.pyright]
pythonPlatform = "All"
pythonVersion = "3.7"
include = ["mosec", "tests", "examples"]

[tool.isort]
profile = "black"

[tool.pylint.master]
load-plugins = "pylint.extensions.docparams,pylint.extensions.docstyle,pylint.extensions.no_self_use"
default-docstring-type = "google"
ignore-paths = ["mosec/_version.py"]

[tool.pylint.format]
max-line-length = 88

[tool.pylint.reports]
output-format = "colorized"
reports = "no"
score = "yes"
max-args = 7

[tool.pylint.messages_control]
disable = []

[pydocstyle]
convention = "google"

[tool.pytest.ini_options]
markers = [
    "arrow: mark a test requires 'pyarrow'",
]
